spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#
#  datasource:
#    hikari:
#      jdbc-url: jdbc:h2:mem:prac;MODE=MySQL;DATABASE_TO_LOWER=true;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
#      driver-class-name: org.h2.Driver
#      username: sa
#      password:

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true