spring:
  main:
    allow-bean-definition-overriding: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true